# Generated by Django 4.2.29 on 2026-03-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('package_name', models.CharField(blank=True, default='', max_length=255)),
                ('version_name', models.CharField(blank=True, default='', max_length=100)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('ml_label', models.CharField(blank=True, default='', max_length=10)),
                ('ml_is_malware', models.BooleanField(null=True)),
                ('ml_probability', models.FloatField(null=True)),
                ('ml_score', models.FloatField(null=True)),
                ('ml_features_matched', models.IntegerField(null=True)),
                ('ahp_score', models.FloatField(null=True)),
                ('ahp_combined', models.FloatField(null=True)),
                ('ahp_verdict', models.CharField(blank=True, default='', max_length=30)),
                ('s_c1', models.FloatField(null=True)),
                ('s_c2', models.FloatField(null=True)),
                ('s_c3', models.FloatField(null=True)),
                ('s_c4', models.FloatField(null=True)),
                ('n_c1', models.IntegerField(null=True)),
                ('n_c2', models.IntegerField(null=True)),
                ('n_c3', models.IntegerField(null=True)),
                ('n_c4', models.IntegerField(null=True)),
                ('full_result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
